name: news
description: Mobile app of Tuoi Tre newspaper

publish_to: 'none'

version: 5.0.9+2025102821


environment:
  sdk: ">=2.7.0 <3.3.0"

dependencies:
  flutter:
    sdk: flutter

  http: 0.13.5
  video_player: 2.4.7
  chewie: 1.4.0
  flutter_inappwebview: 5.8.0
  image_picker: ^0.6.0+2
  email_validator: ^1.0.0
  rflutter_alert: ^1.0.3
#  shared_preferences: 2.2.0
  share: ^0.6.1
  package_info: ^0.4.0+4
#  url_launcher: ^5.0.3
  url_launcher: ^6.1.11
  crypto: ^3.0.0
  sqflite: ^2.0.0

#  firebase_core: 1.12.0
  # firebase_analytics: ^10.6.2
  firebase_core: 1.10.6
#  firebase_core_platform_interface: 4.5.1
#  platform: 3.0.0
  shared_preferences: 2.0.15
  fluttertoast: 8.0.9

  flutter_bloc: ^7.0.1
  equatable: ^1.2.5
  just_debounce_it: ^3.0.0
  cached_network_image: ^3.0.0
  flutter_svg: ^0.22.0
  flutter_phone_direct_caller: ^1.0.1
#  fluttertoast: 8.2.2
  extended_nested_scroll_view: ^3.0.0
  flutter_local_notifications: ^1.0.0
  google_mobile_ads: ^1.0.1

  smartech_base: 3.5.0
  smartech_push: 3.5.0
  smartech_appinbox: 3.5.0

  flutter_widget_from_html_core: ^0.8.5+1
  after_layout: ^1.1.0
  flutter_custom_tabs: ^1.0.4
  flutter_dash_nullsafety: ^1.0.0
  intl: ^0.18.0
  carousel_slider: ^4.2.1
  just_audio: 0.9.31
  fdottedline_nullsafety: 2.0.1
  pin_code_fields: 7.4.0
  bottom_picker: ^2.0.1
  loading_animation_widget: ^1.2.0+4
  flutter_cupertino_datetime_picker: ^3.0.0
  pagination_flutter: ^0.0.8
  diacritic: 0.1.3
  better_player: ^0.0.82

  # Local module
  bookfx:
    path: modules/bookfx/

platforms:
  ios:
    firebase_core: 1.12.0
  android:
    firebase_core: 2.19.0

dependency_overrides:
  platform: 3.1.1

  # Fix Unable to initialize FirebaseApp
  firebase_core_platform_interface: 4.4.1



dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/
    - assets/images/
    - assets/icons/

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: RobotoCondensedBold
      fonts:
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
    - family: RobotoCondensedRegular
      fonts:
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
    - family: RobotoRegular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: SFProDisplayBold
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
    - family: SFProDisplayMedium
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
    - family: SFProDisplayRegular
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
    - family: SFProText
      fonts:
        - asset: assets/fonts/SFProText/SF-Pro-Text-Regular.otf
        - asset: assets/fonts/SFProText/SF-Pro-Text-RegularItalic.otf
          style: italic
        - asset: assets/fonts/SFProText/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/fonts/SFProText/SF-Pro-Text-Bold.otf
          weight: 800
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 800
  #
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
